server:
  port: 9104

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    health-check-url-path: /actuator/health
    #instance-id: ${spring.application.name}-${random.uuid}

spring:
  boot:
    admin:
      discovery:
        converter:
          management-context-path: /actuator
